language: python
python:
    - "2.7"
    - "3.3"
install: pip install mock nose "requests>=1.0" --use-mirrors --upgrade
script: nosetests
notifications:
    email:
        - jturk@sunlightfoundation.com
